apiVersion: v1
kind: Service
metadata: 
  name: rnpcalculator-nd-srv
spec: 
  type: NodePort
  selector:
    app: rnpcalculatorapiservice
  ports:
    - name: rnpcalculatorapiservice
      protocol: TCP
      port: 80
      targetPort: 80